### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by ouyangbob** [plumzero/memo-asn1c#1]

**Comment by ouyangbob** [comment]
c-v2x 的普通消息和加密消息 如何区分呀？

**Comment by plumzero** [comment]
没接触过加密消息，只接触过签名消息

**Comment by ouyangbob** [comment]
对的， 我想说的就是普通消息和签名消息
我想问的是普通消息和签名消息通过什么方式区分呀？目前在做这块的研究，没有看到这块的标准

**Comment by plumzero** [comment]
会有不同的消息结构，如果是普通消息，会使用一般的非安全结构；如果是签名消息，会有特定的签名结构

**Comment by ouyangbob** [comment]
您好， 可否加微信聊下？

**Comment by ouyangbob** [comment]
普通消息是 DSMP -> ASN1 UPER DATA(map、spat、rsi、rsm、bsm)  这个我理解， 但是签名消息不知道通过什么方式区分， 请问是 DSMP莫个属性区分还是啥？

**Comment by plumzero** [comment]
可能你说的签名消息和我说的签名消息结构不太一样，我说的签名消息类似这样
XXXContent ::=  CHOICE  { 
    unsecuredData            Opaque, 
    signedData               SignedData,
    encryptedData            EncryptedData,
    signedCertificateRequest Opaque,
    ...
}
如果是普通消息，就选择unsecuredData，如果是签名消息，就选择第二个；如果是加密消息，就选择第三个

**Comment by ouyangbob** [comment]
> 可能你说的签名消息和我说的签名消息结构不太一样，我说的签名消息类似这样
> XXXContent ::= CHOICE {
> unsecuredData Opaque,
> signedData SignedData,
> encryptedData EncryptedData,
> signedCertificateRequest Opaque,
> ...
> }
> 如果是普通消息，就选择unsecuredData，如果是签名消息，就选择第二个；如果是加密消息，就选择第三个

了解了， 但是普通消息是一个 asn.1 uper 编码的和签名消息不一样， 签名消息是COER，如果这样的话那每次都需要先用COER解码然后如果是普通消息会报错然后在取 unsecuredData 用 uper 解码 感觉不太合理呀

**Comment by plumzero** [comment]
看应用场景，如果是通信，用uper没什么问题。coer一般用做车联网，相比来说还是比较窄的。不同的场景不同的编码格式，这样做也没什么毛病

**Comment by ouyangbob** [comment]
> 看应用场景，如果是通信，用uper没什么问题。coer一般用做车联网，相比来说还是比较窄的。不同的场景不同的编码格式，这样做也没什么毛病

可能是我没表述清楚
普通消息是 DSMP -> DATA（这个是uper 的 MessageFrame）
`MessageFrame ::= CHOICE {
		bsmFrame 	BSM,
		mapFrame 	MAP,
		rsmFrame 	RSM,
		spatFrame 	SPAT,
		rsiFrame 	RSI,
		...
	}`


签名消息呢？ 应该不可能是 DSMP -> DATA(OER编码 V2XSecData)
`V2XSecData ::= SEQUENCE  {
    protocolVersion    Uint8(3),
    content            V2XSecContent
}

V2XSecContent ::=  CHOICE  { 
    unsecuredData            Opaque, 
    signedData               SignedData,
    encryptedData            EncryptedData,
    signedCertificateRequest Opaque,
    ...
}`


如果是上面2种情况， 那如何区分哪条消息是签名消息哪条消息是普通消息？

**Comment by ouyangbob** [comment]
重点是如何区分消息类型， 如何判断Data 是普通消息还是签名消息。

**Comment by plumzero** [comment]
> 
> 
> 重点是如何区分消息类型， 如何判断Data 是普通消息还是签名消息。

不太清楚，这个很难判断。或许你可以先尝试按普通消息解析，如果失败再按签名消息解析。根据二者的比重，决定是将哪种解析放在前面

**Comment by ouyangbob** [comment]
> > 重点是如何区分消息类型， 如何判断Data 是普通消息还是签名消息。
> 
> 不太清楚，这个很难判断。或许你可以先尝试按普通消息解析，如果失败再按签名消息解析。根据二者的比重，决定是将哪种解析放在前面

好的， 谢谢你了啊

**Comment by ouyangbob** [comment]
> > 重点是如何区分消息类型， 如何判断Data 是普通消息还是签名消息。
> 
> 不太清楚，这个很难判断。或许你可以先尝试按普通消息解析，如果失败再按签名消息解析。根据二者的比重，决定是将哪种解析放在前面

能否提供下邮件？或者是您给我发一封邮件ouybt#ehualu.com，有点私事想找您聊下

**Comment by ouyangbob** [comment]
加微信也可以，18101314799
